# Generated by Django 3.0.3 on 2020-02-16 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0002_auto_20200216_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('doctor_name', models.CharField(max_length=200)),
                ('d_sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=8)),
                ('registration_number', models.CharField(max_length=10, null=True)),
                ('years_of_experience', models.IntegerField(null=True)),
                ('establishment_choice', models.CharField(choices=[('owns establishment', 'I own establishment'), ('visit establishment', 'I visit establishment')], default='owns establishment', max_length=25)),
                ('identity_proof', models.ImageField(upload_to='images/')),
                ('medical_registration_proof', models.ImageField(upload_to='images/')),
                ('establishment_proof', models.ImageField(upload_to='images/')),
                ('establishment_name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dep.City')),
                ('city_of_practice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_of_practice', to='dep.City')),
                ('college_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dep.CollegeName')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dep.Location')),
                ('registration_council', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dep.RegistrationCouncil')),
                ('registration_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_year', to='dep.RegistrationYear')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dep.State')),
                ('year_of_completion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='years_of_completion', to='dep.RegistrationYear')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorEstablishmentTimings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField()),
                ('monday', models.CharField(max_length=20)),
                ('tuesday', models.CharField(max_length=20)),
                ('wednesday', models.CharField(max_length=20)),
                ('thursday', models.CharField(max_length=20)),
                ('friday', models.CharField(max_length=20)),
                ('saturday', models.CharField(max_length=20)),
                ('sunday', models.CharField(max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dep.Doctor')),
            ],
        ),
    ]
