# Generated by Django 3.0.3 on 2020-02-16 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0003_doctor_doctorestablishmenttimings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('p_emailid', models.EmailField(max_length=254)),
                ('p_name', models.CharField(max_length=200)),
                ('p_sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=8)),
                ('p_occupation', models.CharField(max_length=100)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dep.City')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dep.State')),
            ],
        ),
        migrations.CreateModel(
            name='Phq9Questions',
            fields=[
                ('q_id', models.IntegerField(primary_key=True, serialize=False)),
                ('question_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RelationTable',
            fields=[
                ('relation_no', models.IntegerField(primary_key=True, serialize=False)),
                ('relation_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Phq9Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.IntegerField()),
                ('q2', models.IntegerField()),
                ('q3', models.IntegerField()),
                ('q4', models.IntegerField()),
                ('q5', models.IntegerField()),
                ('q6', models.IntegerField()),
                ('q7', models.IntegerField()),
                ('q8', models.IntegerField()),
                ('q9', models.IntegerField()),
                ('q10', models.IntegerField()),
                ('date', models.DateField()),
                ('total', models.IntegerField()),
                ('p_userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dep.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Phq9Answer',
            fields=[
                ('answer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('phq9_option', models.CharField(choices=[('Not at all', 'Not at all'), ('Several days', 'Several days'), ('More than half days', 'More than half days'), ('Nearly every days', 'Nearly every days')], max_length=30)),
                ('score', models.IntegerField()),
                ('que', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dep.Phq9Questions')),
            ],
        ),
    ]
