# Generated by Django 3.0.3 on 2020-02-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0004_patient_phq9answer_phq9questions_phq9score_relationtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('q_id', models.IntegerField(primary_key=True, serialize=False)),
                ('question_name', models.CharField(max_length=200)),
            ],
        ),
    ]
