# Generated by Django 3.0.3 on 2020-02-16 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0006_connectionpatientwellwishers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConnectionPatientWellWishers',
        ),
    ]
