# Generated by Django 3.0.3 on 2020-02-16 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0007_delete_connectionpatientwellwishers'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellWishers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionPatientWellWishers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dep.Patient')),
                ('relation_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dep.RelationTable')),
                ('well_wisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dep.WellWishers')),
            ],
        ),
    ]
