# Generated by Django 3.0.3 on 2020-02-16 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0008_connectionpatientwellwishers_wellwishers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wellwishers',
            name='id',
        ),
        migrations.AlterField(
            model_name='wellwishers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
