# Generated by Django 3.0.3 on 2020-02-20 11:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0011_auto_20200220_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUploadedByWellWishers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('video_description', models.CharField(max_length=500)),
                ('video', models.FileField(upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'ogg', 'wmv', 'flv', 'mkv'])])),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dep.Patient')),
                ('well_wisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dep.WellWishers')),
            ],
        ),
        migrations.CreateModel(
            name='ImageUploadedByWellWisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image_description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='images/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dep.Patient')),
                ('well_wisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dep.WellWishers')),
            ],
        ),
    ]
