# Generated by Django 3.0.3 on 2020-03-04 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0012_imageuploadedbywellwisher_videouploadedbywellwishers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_personFromWorkPlace',
        ),
    ]
