# Generated by Django 3.0.3 on 2020-03-04 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0013_remove_user_is_personfromworkplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_friend',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_relative',
        ),
    ]
