# Generated by Django 3.0.3 on 2020-03-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0014_auto_20200304_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_receptionist',
            field=models.BooleanField(default=False),
        ),
    ]
