# Generated by Django 3.0.3 on 2020-03-08 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0016_connectiondoctorreceptionist_receptionist'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDoctorPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_time', models.TimeField()),
                ('date_of_appointment', models.DateField()),
                ('accept_appointment', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dep.Doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dep.Patient')),
            ],
        ),
    ]
