# Generated by Django 3.0.3 on 2020-03-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0017_appointmentdoctorpatient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentdoctorpatient',
            old_name='slot_time',
            new_name='slot_time2',
        ),
        migrations.AddField(
            model_name='appointmentdoctorpatient',
            name='slot_time1',
            field=models.TimeField(null=True),
        ),
    ]
