# Generated by Django 3.0.3 on 2020-03-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0018_auto_20200309_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentdoctorpatient',
            old_name='slot_time1',
            new_name='slot_time1_from',
        ),
        migrations.RemoveField(
            model_name='appointmentdoctorpatient',
            name='slot_time2',
        ),
        migrations.AddField(
            model_name='appointmentdoctorpatient',
            name='slot_time1_to',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='appointmentdoctorpatient',
            name='slot_time2_from',
            field=models.TimeField(null=True),
        ),
    ]
