# Generated by Django 3.0.3 on 2020-03-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0020_appointmentdoctorpatient_slot_time2_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentdoctorpatient',
            name='slot_time1_from',
        ),
        migrations.RemoveField(
            model_name='appointmentdoctorpatient',
            name='slot_time1_to',
        ),
        migrations.RemoveField(
            model_name='appointmentdoctorpatient',
            name='slot_time2_from',
        ),
        migrations.RemoveField(
            model_name='appointmentdoctorpatient',
            name='slot_time2_to',
        ),
        migrations.AddField(
            model_name='appointmentdoctorpatient',
            name='session_1_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentdoctorpatient',
            name='session_1_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentdoctorpatient',
            name='session_2_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentdoctorpatient',
            name='session_2_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
