# Generated by Django 3.0.3 on 2020-03-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0022_auto_20200309_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdoctorpatient',
            name='session_1_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentdoctorpatient',
            name='session_1_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentdoctorpatient',
            name='session_2_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentdoctorpatient',
            name='session_2_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
