# Generated by Django 3.0.3 on 2020-03-10 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0023_auto_20200309_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentdoctorpatient',
            name='accept_appointment',
        ),
    ]
