# Generated by Django 3.0.3 on 2020-03-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0024_remove_appointmentdoctorpatient_accept_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentdoctorpatient',
            name='patient',
        ),
    ]
