# Generated by Django 3.0.3 on 2020-03-10 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0025_remove_appointmentdoctorpatient_patient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppointmentDoctorPatient',
            new_name='DoctorSessionTime',
        ),
    ]
