# Generated by Django 3.0.3 on 2020-03-10 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0026_auto_20200310_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDoctorPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_time', models.TimeField(null=True)),
                ('date', models.DateField()),
                ('is_accept', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dep.Doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dep.Patient')),
            ],
        ),
    ]
