# Generated by Django 3.0.3 on 2020-03-10 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0027_appointmentdoctorpatient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentdoctorpatient',
            old_name='date',
            new_name='date_of_appointment',
        ),
    ]
