# Generated by Django 3.0.3 on 2020-03-19 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0029_auto_20200315_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name_of_report', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dep.Patient')),
            ],
        ),
    ]
