# Generated by Django 3.0.3 on 2020-03-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0032_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
