# Generated by Django 3.0.3 on 2020-03-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0033_doctor_is_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='fees',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
    ]
