# Generated by Django 3.0.3 on 2020-03-22 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0034_doctor_fees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='d_sex',
            new_name='gender',
        ),
    ]
