# Generated by Django 3.0.3 on 2020-03-22 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0035_auto_20200322_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='fees',
            new_name='price',
        ),
    ]
