# Generated by Django 3.0.3 on 2020-03-24 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0036_auto_20200322_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratedailyactivities',
            name='relation_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dep.RelationTable'),
        ),
    ]
