# Generated by Django 3.0.3 on 2020-03-25 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0037_ratedailyactivities_relation_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientTreatmentAndMedicineInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=500)),
                ('name_of_treatment', models.CharField(max_length=500)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dep.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dep.Patient')),
            ],
        ),
    ]
