# Generated by Django 3.0.3 on 2020-03-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0038_patienttreatmentandmedicineinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttreatmentandmedicineinfo',
            name='timestamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
