# Generated by Django 3.0.3 on 2020-04-02 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0040_auto_20200331_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSessionTimeOfTeleMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_1_from', models.TimeField(blank=True, null=True)),
                ('session_1_to', models.TimeField(blank=True, null=True)),
                ('session_2_from', models.TimeField(blank=True, null=True)),
                ('session_2_to', models.TimeField(blank=True, null=True)),
                ('date_of_appointment', models.DateField()),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dep.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentDoctorPatientOfTeleMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_time', models.TimeField(null=True)),
                ('date_of_appointment', models.DateField()),
                ('is_accept', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dep.Doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dep.Patient')),
            ],
        ),
    ]
