# Generated by Django 3.0.3 on 2020-04-04 07:26

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0043_auto_20200404_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='degree',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='location_of_clinic',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='telemedicine_facility',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
