# Generated by Django 3.0.3 on 2020-04-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0044_auto_20200404_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='telemedicine_facility',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=10),
        ),
    ]
