# Generated by Django 3.0.3 on 2020-04-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0045_auto_20200404_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='reports_needed_for_telemedicine',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
