# Generated by Django 3.0.3 on 2020-04-10 08:03

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0047_auto_20200410_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='degree',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='location_of_clinic',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='telemedicine_facility',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=10, null=True),
        ),
    ]
