# Generated by Django 3.0.3 on 2020-04-10 10:02

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0048_auto_20200410_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, null=True, region=None),
        ),
    ]
