# Generated by Django 3.0.3 on 2020-05-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0051_auto_20200508_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdoctorpatient',
            name='is_reject',
            field=models.BooleanField(default=False),
        ),
    ]
