# Generated by Django 3.0.3 on 2020-05-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dep', '0053_appointmentdoctorpatientoftelemedicine_is_reject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentdoctorpatientoftelemedicine',
            name='is_reject',
        ),
    ]
