from django.urls import path, include, re_path
from .views import patient, main, doctor, wellwisher, receptionist, moderator


urlpatterns = [
    path('', main.home, name='home'),
    path('ajax/load_cities', patient.load_cities, name='ajax_load_cities'),
    path('ajax/load_locations', doctor.load_location, name='ajax_load_location'),


    path('patient/', include(([
        path('<int:pk>/', patient.PatientUpdateView.as_view(), name='add_cities_state'),
        path('', patient.index, name='index'),
        path('phq9_questions/', patient.phq9_questions, name='phq9_questions'),
        path('add_well_wishers/friend/', patient.AddWellWisher1View.as_view(), name='add_well_wisher1'),
        path('add_well_wishers/relative/', patient.AddWellWisher2View.as_view(), name='add_well_wisher2'),
        path('add_well_wishers/colleague/', patient.AddWellWisher3View.as_view(), name='add_well_wisher3'),
        path('memories/', patient.ImagesListView.as_view(), name='list_images'),
        path('memories_videos/', patient.VideoListView.as_view(), name='list_videos'),
        path('choose_doctor_for_appointment/', patient.choose_doctor_from_dashboard, name='choose_doctors_dashboard'),
        path('choose_doctors_for_telemedicine', patient.choose_doctors_for_telemedicine,
             name='choose_doctors_for_telemedicine'),
        path('doctor_information/<pk>', patient.DoctorInformationView.as_view(), name='doctor_information'),
        path('doctor_telemedicine_information/<pk>', patient.DoctorTeleMedicineInformationView.as_view(),
             name='doctor_telemedicine_information'),
        re_path(r'^book_appointment/', patient.load_slot_timings, name='ajax_load_slot_timings'),
        re_path(r'^book_appointment_for_telemedicine/', patient.load_slot_timings_for_telemedicine,
                name='ajax_load_slot_timings_telemedicine'),
        re_path(r'^doctor_information/(?P<doctor>)', patient.BookAppointmentView.as_view(), name='book_appointment'),
        re_path(r'^doctor_telemedicine_information/(?P<doctor>)', patient.BookAppointmentForTeleMedicineView.as_view(),
                name='book_appointment_for_telemedicine'),
        path('check_appointments/', patient.check_appointment_of_patient, name='check_appointments'),
        path('check_telemedicine_appointments/', patient.check_telemedicine_appointments_of_patient,
             name='check_telemedicine_appointments'),
        re_path(r'^check_telemedicine_appointments/cancel_tele_appointment/(?P<cancel>)', patient.cancel_tele_appointments,
                name='cancel_tele_appointment'),
        re_path(r'^check_appointments/cancelled/(?P<cancel>)', patient.cancel_appointments, name='cancel_appointment'),
        re_path(r'^check_appointments/reschedule/(?P<reschedule>)', patient.reschedule_appointments,
                name='reschedule_appointment'),
        path('upload_report/', patient.upload_report, name='upload_patient_report'),
        path('see_uploaded_report/', patient.HealthReportListView.as_view(), name='see_uploaded_report'),
        path('remove_photo/', patient.remove_photo, name='remove_photo'),
        path('remove_video/', patient.remove_video, name='remove_video'),
        path('change_well_wisher/friend', patient.ChangeWellWisher1.as_view(), name='change_well_wisher1'),
        path('change_well_wisher/relative', patient.ChangeWellWisher2.as_view(), name='change_well_wisher2'),
        path('change_well_wisher/colleague', patient.ChangeWellWisher3.as_view(), name='change_well_wisher3'),
        path('remove_report/', patient.remove_report, name='remove_report'),
    ], 'dep'), namespace='patient')),

    path('doctor/', include(([
        path('', doctor.index, name='index'),
        path('registration/<pk>', doctor.DoctorProfileDetailsView.as_view(), name='profile_details'),
        path('education/<pk>', doctor.DoctorEducationQualificationView.as_view(), name='education_qualification'),
        # path('connect_clinic/<pk>', doctor.DoctorEstablishmentChoiceView.as_view(), name='connect_clinic'),
        path('clinic_details/<pk>', doctor.DoctorEstablishmentDetailsView.as_view(), name='clinic_details'),
        path('practice_suggestions/', doctor.DoctorPracticeSuggestionsView.as_view(), name='practice_suggestions'),
        # path('clinic_check/<pk>', doctor.DoctorEstablishmentDetailsView.as_view(), name='clinic_check'),
        path('identity_proof/<pk>', doctor.DoctorIdentityProofView.as_view(), name='identity_proof'),
        path('registration_proof/<pk>', doctor.DoctorMedicalRegistrationProofView.as_view(), name='registration_proof'),
        path('clinic_proof/<pk>', doctor.DoctorEstablishmentProofView.as_view(), name='establishment_proof'),
        path('photo_proof/<pk>', doctor.DoctorPhotoProofView.as_view(), name='photo_proof'),
        path('extra_info/<pk>', doctor.DoctorExtraInformationView.as_view(), name='add_extra_information'),
        path('add_receptionist/', doctor.AddReceptionistView.as_view(), name='add_receptionist'),
        path('check_patient/', doctor.check_patient, name='check_patient'),
        path('check_patient_of_telemedicine/', doctor.check_patient_of_telemedicine, name='check_patient_of_telemedicine'),
        path('chart_phq9_question/', doctor.chart_phq9_question, name='chart_phq9_question'),
        path('chart_daily_report/', doctor.chart_daily_report, name='chart_daily_report'),
        path('add_reports_for_telemedicine/<pk>', doctor.AddReportsForTelemedicine.as_view(),
             name='add_reports_for_telemedicine'),

        re_path('^check_patient_of_telemedicine/review_report/check_phq9_graph/(?P<patient>)', doctor.phq9_questions_report,
                name='phq9_questions_report'),
        re_path('^check_patient/review_report/check_phq9_graph/(?P<patient>)', doctor.phq9_questions_report,
                name='phq9_questions_report'),

        re_path('^check_patient_of_telemedicine/review_report/check_daily_activity_graph/(?P<patient>)', doctor.
                daily_activity_report,name='daily_activity_report'),
        re_path('^check_patient/review_report/check_daily_activity_graph/(?P<patient>)', doctor.daily_activity_report,
                name='daily_activity_report'),

        re_path('^check_patient_of_telemedicine/review_report/give_prescriptions/(?P<patient>)', doctor.give_prescriptions,
                name='give_prescriptions'),
        re_path('^check_patient/review_report/give_prescriptions/(?P<patient>)', doctor.give_prescriptions,
                name='give_prescriptions'),

        re_path('^check_patient_of_telemedicine/review_report/review_uploaded_reports/(?P<patient>)', doctor.
                review_uploaded_reports, name='review_uploaded_reports'),
        re_path('^check_patient/review_report/review_uploaded_reports/(?P<patient>)', doctor.review_uploaded_reports,
                name='review_uploaded_reports'),

        re_path('^check_patient_of_telemedicine/review_report/(?P<patient>)$', doctor.review_report,
                name='telemedicine_review_report'),
        re_path('^check_patient/review_report/(?P<patient>)$', doctor.review_report, name='review_report'),
    ], 'dep'), namespace='doctor')),

    path('wellwisher/', include(([
        path('', wellwisher.well_wisher_dasboard, name='index'),
        path('add_patient/', wellwisher.add_patient, name='add_patients'),
        path('access/<pk>', wellwisher.well_wisher_dashboard, name='well_wisher_access'),
        path('memories/', wellwisher.ImagesListView.as_view(), name='list_images'),
        path('memories_videos/', wellwisher.VideoListView.as_view(), name='list_videos'),
        re_path(r'^access/images/(?P<patient>)', wellwisher.upload_images),
        re_path(r'^access/videos/(?P<patient>)', wellwisher.upload_videos),
        re_path(r'^access/(?P<patient>)', wellwisher.rate_daily_activity),
        re_path(r'^remove_patient/(?P<patient>)', wellwisher.remove_patient, name='remove_patient'),
        path('remove_photo/', wellwisher.remove_photo, name='remove_photo'),
        path('remove_video/', wellwisher.remove_video, name='remove_video'),
    ], 'dep'), namespace='wellwisher')),

    path('receptionist/', include(([
        path('', receptionist.ReceptionistDashboardView.as_view(), name='index'),
        path('add_doctor/', receptionist.add_doctor, name='add_doctor'),
        path('access/<pk>', receptionist.receptionist_dashboard, name='doctor_access'),
        re_path(r'^remove_doctor/(?P<doctor>)', receptionist.remove_doctor, name='remove_doctor'),
        re_path(r'^access/patient_appointment_information/approve_appointment/',
                receptionist.approve_appointment, name='approve_appointment'),
        re_path(r'access/patient_telemedicine_appointment_information/approve_payment',
                receptionist.approve_payment, name='approve_telemedicine_payment'),
        re_path(r'^access/patient_appointment_information/reject_appointment/',
                receptionist.reject_appointment, name='reject_appointment'),
        re_path(r'^access/patient_appointment_information/',
                receptionist.patient_appointment_information, name='patient_appointment_information'),
        re_path(r'^access/add_sessions_of_telemedicine/(?P<doctor>)', receptionist.add_timings_of_telemedicine,
                name='add_sessions_of_telemedicine'),
        re_path(r'^access/change_sessions_of_telemedicine/(?P<doctor>)', receptionist.change_timings_of_telemedicine,
                name='change_timings_of_telemedicine'),
        re_path(r'^access/patient_telemedicine_appointment_information/', receptionist.
                patient_telemedicine_appointment_information, name='patient_telemedicine_appointment_information'),
        re_path(r'^access/change_sessions/(?P<doctor>)', receptionist.change_timings, name='change_timings'),
        re_path(r'^access/(?P<doctor>)', receptionist.add_timings, name='add_sessions'),
    ], 'dep'), namespace='receptionist')),

    path('moderator/', include(([
        path('', moderator.index, name='index'),
        path('list_pending_doctors/', moderator.PendingDoctorsListView.as_view(), name='list_pending_doctors'),
        re_path('list_pending_doctors/check_doctor/(?P<doctor>)', moderator.check_doctors, name='check_doctors'),
    ], 'dep'), namespace='moderator')),

]
